name: JacquiShepherd
favicon: null
layout_spectrum: 0.5104922021273524
typography_spectrum: 0.2356320160906762
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a8b5bc'
    - '#e53601'
    - '#262100'
    - '#967238'
    - '#ffa806'
  brandStrength: 0.5625
  lightness: 0.12196347769349813
  saturation: 0.859204467618838
  rhythmicContrast: 0.26340705365873873
purpose: []
